### PR TITLE
fixed bug of stoplevel for instant orders and some translations made for EarnForex

### PR DESCRIPTION
**Pull request by jfdelosrios**

### CODE REVIEW

**Comment by EarnForex** [comment]
Thanks!

**Comment by jfdelosrios** [comment]
hi.

I only know spanish and english, you must review the alerts for "Trade allowed " for others languages.

**Comment by jfdelosrios** [comment]
Excuse me, do you have telegram or whatsapp? I found other bug

**Comment by EarnForex** [comment]
You can post them here or send the info via webmaster@earnforex.com.

**Pull request merged**
