### PR TITLE
Update Position Sizer.mqh

### PR DESCRIPTION
**Pull request by amrali-eg**
Improved currency conversions: for example, fixed USDCHN (and others) on EUR account currency.

### CODE REVIEW

**Comment by EarnForex** [comment]
Interesting. Which broker/account did you test it on with the USDCHN pair?
Also, why did you decide to do away with the global variables to store the found conversion pairs?

**Comment by amrali-eg** [comment]
I tested USDCHN on ICMarkets MT5 demo with Euro account currency.

The main reason for the global variables was to cache the conversions pairs to speed lookups in the terminal's symbols list (SymbolsTotal(false) is actually slow). But as a side effect, many global and dummy variables are used (as in CalculatePortfolioRisk()), or, the same lookup code is repeated all over the place (as in GetSwapData()). 

On the other hand, searching a small list (< 100 items) of short strings (6-10 chars, each) that is cached in memory is a trivial operation. No need for caching in global/dummy variables. The search is also implemented as a recursive function.

2nd issue: fixed margin calculation in the CalculateMargin() function.

**Comment by EarnForex** [comment]
Hello!

OK, I've been able to test this for some time now and it looks great! One note though. I would suggest preserving the string variables for margin, profit, and swap conversion pairs as string operations aren't extremely fast here and will be performed on each tick (unless I am missing something). Otherwise, you'd need to remove the references to the removed variables from the Position Sizer.mq5 file - or it will throw compilation errors.

Thank you!

**Comment by amrali-eg** [comment]
I did some benchmarks using GetMicrosecondCount() to check the performance of string variables vs CachedArray and CachedHasMap.
Nearly, all versions took a fraction of a millisecond to find the correct currency pair.
[benchmark_results.txt](https://github.com/EarnForex/PositionSizer/files/10412595/benchmark_results.txt)

**Comment by EarnForex** [comment]
If you were testing it on CHF/JPY, I guess this condition in `GetSymbolByCurrencies()` always returned _true_, so it's never got to the actual array part:
`if (SymbolExist(base_currency + profit_currency, is_custom))`

Or is there something that I didn't notice?

**Comment by amrali-eg** [comment]
It will search for profit/account currency pair to convert profits or losses to account currency. On my EUR account, it searches for JPY/EUR, then scan the cached list for a matching prefixed or suffixed symbols, then scan again reversed as EUR/JPY which is found.

**Pull request merged**
