### PR TITLE
improvements

### PR DESCRIPTION
**Pull request by jfdelosrios**
Various changes:
1. ERR_OBJECT_NOT_FOUND error management is improved.
2. ERR_GLOBALVARIABLE_NOT_FOUND error management is improved.
3. ERR_FILE_NOT_EXIST error management is improved.
4. Stop loss positioning analysis for instant opening orders is improved.
5. Detection of trading disabled by the user is improved.

### CODE REVIEW

**Comment by jfdelosrios** [comment]
Hello. I am attentive to any comments or recommendations.

**Comment by EarnForex** [comment]
Hello!

Thank you for your changes on autotrading detection and stoplevel application. Could you please explain your changes regarding error handling? I don't understand them at all.

**Comment by jfdelosrios** [comment]
Hello.

Please, Could you tell me which changes you do not undertand?

**Comment by EarnForex** [comment]
All the changes concerning the errors. Why are you checking and resetting _LastError? Why are you calling ExpertRemove() or returning INIT_FAILED in .mq5?

**Comment by jfdelosrios** [comment]
1. Why are you checking and resetting _LastError?: _LastError tells us if a function had a problem in its work.
2. Why are you returning INIT_FAILED in .mq5?: INIT_FAILED tells us if a problem ocurred when the EA ran OnInit function.
3. Why are you calling ExpertRemove(): I use this function in order to finish the EA if a there was a problem and this problem was not managed, this for security of the trader.

**Comment by EarnForex** [comment]
Thank you for these explanations! Could you please provide an example of an unmanaged problem that would merit INIT_FAILED or expert removal?

**Comment by jfdelosrios** [comment]
if a object or variable or function did not run good and the ea does not manage this problem, then, unexpected behavior could occur.

if the EA manages good the problems, then, the ea will not run ExpertRemove() and INIT_FAILED.

It is important to remember than the EA helps to traders to manage money.

**Comment by jfdelosrios** [comment]
For example, in this moment some times the EA is showing ERR_CHART_NO_REPLY, I am waiting to find where is the bug.

**Comment by EarnForex** [comment]
This may certainly serve well for debugging, but I'm not convinced that adding that to the main functionality would be good for users. They certainly wouldn't like the EA unloading or failing to initialize (wasting all their changes to input parameters) on non-critical issues.

**Comment by jfdelosrios** [comment]
Do you have a branch for debugging?

**Comment by EarnForex** [comment]
No, but those could be wrapped into some #ifdef conditions.

**Comment by jfdelosrios** [comment]
Ok, I go to do it and I send again the pull request

**Comment by EarnForex** [comment]
Hello Jorge,

Perhaps, it makes sense to add the changes for autotrading detection and stoplevel checks as a separate pull request?

**Comment by jfdelosrios** [comment]
Hello,

I think creating a new branch for debugging would be a great idea.

**Comment by EarnForex** [comment]
Hello!

I've just created it.

**Comment by jfdelosrios** [comment]
ok.

**Pull request closed without merging**
